# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: img.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='img.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\timg.proto\"\x17\n\x08ImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"\x1d\n\x0eImageAttribute\x12\x0b\n\x03msg\x18\x01 \x01(\x0c\x32;\n\nImageProto\x12-\n\rClassifyImage\x12\t.ImageMsg\x1a\x0f.ImageAttribute\"\x00\x62\x06proto3')
)




_IMAGEMSG = _descriptor.Descriptor(
  name='ImageMsg',
  full_name='ImageMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='ImageMsg.img', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=36,
)


_IMAGEATTRIBUTE = _descriptor.Descriptor(
  name='ImageAttribute',
  full_name='ImageAttribute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='ImageAttribute.msg', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['ImageMsg'] = _IMAGEMSG
DESCRIPTOR.message_types_by_name['ImageAttribute'] = _IMAGEATTRIBUTE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageMsg = _reflection.GeneratedProtocolMessageType('ImageMsg', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEMSG,
  '__module__' : 'img_pb2'
  # @@protoc_insertion_point(class_scope:ImageMsg)
  })
_sym_db.RegisterMessage(ImageMsg)

ImageAttribute = _reflection.GeneratedProtocolMessageType('ImageAttribute', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEATTRIBUTE,
  '__module__' : 'img_pb2'
  # @@protoc_insertion_point(class_scope:ImageAttribute)
  })
_sym_db.RegisterMessage(ImageAttribute)



_IMAGEPROTO = _descriptor.ServiceDescriptor(
  name='ImageProto',
  full_name='ImageProto',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=69,
  serialized_end=128,
  methods=[
  _descriptor.MethodDescriptor(
    name='ClassifyImage',
    full_name='ImageProto.ClassifyImage',
    index=0,
    containing_service=None,
    input_type=_IMAGEMSG,
    output_type=_IMAGEATTRIBUTE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGEPROTO)

DESCRIPTOR.services_by_name['ImageProto'] = _IMAGEPROTO

# @@protoc_insertion_point(module_scope)
