# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import img_pb2 as img__pb2


class ImageProtoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ClassifyImage = channel.unary_unary(
        '/ImageProto/ClassifyImage',
        request_serializer=img__pb2.ImageMsg.SerializeToString,
        response_deserializer=img__pb2.ImageAttribute.FromString,
        )


class ImageProtoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ClassifyImage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImageProtoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ClassifyImage': grpc.unary_unary_rpc_method_handler(
          servicer.ClassifyImage,
          request_deserializer=img__pb2.ImageMsg.FromString,
          response_serializer=img__pb2.ImageAttribute.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ImageProto', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
